version: '3'
services:
  rasa:
    image: rasa/rasa:3.6.0
    volumes:
      - ./:/app
    ports:
      - "5005:5005"
    command: run --enable-api --cors "*" --port 5005
    working_dir: /app
    depends_on:
      - rasa-actions
    networks:
      - rasa-network
  rasa-actions:
    build:
      context: .
      dockerfile: ./action_server_docker/Dockerfile
    container_name: rasa-project-rasa-actions
    volumes:
      - ./actions:/app/actions
      - ./requirements-actions.txt:/app/requirements-actions.txt
    ports:
      - "5055:5055"
    networks:
      - rasa-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - rasa
    networks:
      - rasa-network
networks:
  rasa-network:
    driver: bridge
